project:
  type: website
  output-dir: ../docs

website:
  title: "Land, River and Seascape Genomics"

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - Teachers.qmd
      - Readings.qmd
  

  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Sunday"
        contents:
          - Basic-Population-Genetics.qmd
          - basicR.qmd
          - basic-bash.qmd
      - section: "Monday"
        contents:
          - land-river-sea.qmd
          - maps-spatial-data.qmd
      - section: "Tuesday"
        contents:   
          - genetic-dif.qmd
          - RDA.qmd
      - section: "Wednesday"
        contents:   
          - geneflow.qmd
      - section: "Thursday"
        contents:  
         - resistance.qmd
         - GDM.qmd
         - biophysical.qmd
      - section: "Friday"
        contents:  
         - GEA.qmd
          
       
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

sidebar:
  contents: auto

# number-sections: true
# crossref:
#   chapters: true